from dao import MilvusDAO

data_models = [
    {"id": "100001", "fields": ["machine_id", "status", "last_maintenance_date"], "tags": ["机械", "维护"]},
    {"id": "100002", "fields": ["product_id", "production_date", "quantity", "quality_status"],
     "tags": ["生产", "质量控制"]},
    {"id": "100003", "fields": ["employee_id", "name", "position", "department"], "tags": ["人力资源", "员工管理"]},
    {"id": "100004", "fields": ["order_id", "customer_id", "order_date", "delivery_date"],
     "tags": ["销售", "订单处理"]},
    {"id": "100005", "fields": ["sensor_id", "reading", "timestamp"], "tags": ["传感器数据", "监控"]},
    {"id": "100006", "fields": ["inventory_id", "item_name", "quantity_in_stock"], "tags": ["库存", "仓储"]},
    {"id": "100007", "fields": ["log_id", "error_code", "timestamp", "resolved"], "tags": ["系统日志", "IT"]},
    {"id": "100008", "fields": ["project_id", "project_name", "start_date", "end_date"], "tags": ["项目管理", "计划"]},
    {"id": "100009", "fields": ["supplier_id", "name", "contact", "product_type"], "tags": ["供应链", "供应商"]},
    {"id": "100010", "fields": ["audit_id", "department", "audit_date", "findings"], "tags": ["审计", "合规"]},
    {"id": "100011", "fields": ["transaction_id", "amount", "transaction_date", "customer_id"],
     "tags": ["交易", "财务"]},
    {"id": "100012", "fields": ["device_id", "location", "status", "last_checked"], "tags": ["设备", "位置跟踪"]},
    {"id": "100013", "fields": ["recipe_id", "ingredients", "cooking_time", "serving_size"],
     "tags": ["配方", "食品加工"]},
    {"id": "100014", "fields": ["batch_id", "batch_size", "start_time", "end_time"], "tags": ["批次", "生产调度"]},
    {"id": "100015", "fields": ["maintenance_id", "equipment_id", "date", "actions"], "tags": ["保养", "设备管理"]},
    {"id": "100016", "fields": ["inspection_id", "inspector", "date", "findings"], "tags": ["检查", "质量保证"]},
    {"id": "100017", "fields": ["shipment_id", "origin", "destination", "shipment_date"], "tags": ["运输", "物流"]},
    {"id": "100018", "fields": ["work_order_id", "description", "assigned_to", "due_date"],
     "tags": ["工作订单", "任务分配"]},
    {"id": "100019", "fields": ["patient_id", "name", "diagnosis", "treatment_plan"], "tags": ["病患", "医疗服务"]},
    {"id": "100020", "fields": ["ticket_id", "issue", "reported_by", "resolution_status"],
     "tags": ["支持票据", "客户服务"]},
    {"id": "100021", "fields": ["asset_id", "type", "value", "depreciation"], "tags": ["资产", "财务管理"]},
    {"id": "100022", "fields": ["energy_consumption", "time_period", "peak_usage"], "tags": ["能源消耗", "能源管理"]},
    {"id": "100023", "fields": ["chemical_id", "quantity", "storage_location"], "tags": ["化学品", "安全存储"]},
    {"id": "100024", "fields": ["safety_incident_id", "incident_type", "date_reported"],
     "tags": ["安全事故", "事故报告"]},
    {"id": "100025", "fields": ["quality_check_id", "product_id", "inspection_results"],
     "tags": ["质量检查", "产品检验"]},
    {"id": "100026", "fields": ["employee_training_id", "course_name", "completion_date"],
     "tags": ["员工培训", "教育发展"]},
    {"id": "100027", "fields": ["environmental_impact_id", "impact_type", "mitigation_measures"],
     "tags": ["环境影响", "可持续发展"]},
    {"id": "100028", "fields": ["cost_center_id", "budget", "actual_spending"], "tags": ["成本中心", "财务规划"]},
    {"id": "100029", "fields": ["facility_id", "location", "capacity"], "tags": ["设施", "设施管理"]},
    {"id": "100030", "fields": ["contract_id", "vendor", "contract_terms"], "tags": ["合同", "供应商管理"]},
    {"id": "100031", "fields": ["risk_assessment_id", "risk_factor", "mitigation_plan"],
     "tags": ["风险评估", "风险管理"]},
    {"id": "100032", "fields": ["procurement_order_id", "item", "quantity_ordered"], "tags": ["采购订单", "采购"]},
    {"id": "100033", "fields": ["product_design_id", "design_specifications", "designer"],
     "tags": ["产品设计", "研发"]},
    {"id": "100034", "fields": ["regulatory_compliance_id", "regulation", "compliance_status"],
     "tags": ["法规合规", "合规性"]},
    {"id": "100035", "fields": ["customer_feedback_id", "feedback_type", "resolution_status"],
     "tags": ["客户反馈", "客户关系"]},
    {"id": "100036", "fields": ["waste_management_id", "waste_type", "disposal_method"],
     "tags": ["废物管理", "环境保护"]},
    {"id": "100037", "fields": ["maintenance_schedule_id", "equipment_id", "scheduled_date"],
     "tags": ["维护计划", "设备保养"]},
    {"id": "100038", "fields": ["inventory_restock_id", "item_id", "restock_level"], "tags": ["库存补货", "库存管理"]},
    {"id": "100039", "fields": ["training_program_id", "program_name", "participants"],
     "tags": ["培训计划", "人力资源"]},
    {"id": "100040", "fields": ["production_target_id", "target_quantity", "deadline"],
     "tags": ["生产目标", "生产管理"]}
]

if __name__ == '__main__':
    milvus_dao = MilvusDAO()
    for data_model in data_models:
        milvus_dao.embed_model(**data_model)
